
server:
  #默认端口
  port: 7001
  tomcat:
    uri-encoding: UTF-8

spring:
  application:
    #微服务 发现端
    name: product
eureka:
  client:
    serviceUrl:
      # 访问路径要后缀eureka 大坑
      defaultZone: http://localhost:8761/eureka/eureka/

